/**
 * TSDocs Runtime Configuration
 * Auto-generated by mint-tsdocs during documentation build.
 * Loaded globally as a custom script for all documentation pages.
 *
 * This provides runtime configuration to TSDocs components (RefLink, PageLink, etc.)
 * without requiring imports between snippet files.
 *
 * @generated
 */
(function() {
  'use strict';

  // Global TSDocs configuration accessible to all components
  window.TSDOCS_CONFIG = {
    basePath: "/core-editor",
    packageName: "core-editor",
    generatedAt: "2026-07-06T20:12:08.666Z"
  };

  // Helper function to generate absolute path for an API reference
  window.getRefPath = function(refId) {
    var segments = refId.split('.').filter(function(s) { return s.length > 0; });
    return segments.length > 0
      ? window.TSDOCS_CONFIG.basePath + '/' + segments.join('/')
      : window.TSDOCS_CONFIG.basePath;
  };
})();
