replicaCount: 1
name: nanoforge-docs
image:
  repository: ghcr.io/nanoforge-dev/docs
  tag: sha256-9dddfbda5325b2bafeca2081dc890501aa30a492089e1b4b76dd5dfb33b73557
imagePullSecret: nanoforge-docker-token
routes:
- port: 80
  match: Host(`docs.nanoforge.eu`)
