// @ts-nocheck
/**
 * Valid API Reference IDs
 * Auto-generated by mint-tsdocs during documentation build.
 * Used by RefLink component for runtime validation.
 *
 * @generated
 */

// Expose VALID_REFS on window for use by RefLink component
// This avoids ES6 module import issues with .jsx MIME types
if (typeof window !== 'undefined') {
  window.VALID_REFS = new Set([
  "core-editor",
  "core-editor.CoreEvents",
  "core-editor.EditorEvents",
  "core-editor.EventEmitter",
  "core-editor.EventEmitter.constructor",
  "core-editor.EventEmitter.emit",
  "core-editor.EventEmitter.on",
  "core-editor.EventEmitter.runEvents",
  "core-editor.NanoforgeClient",
  "core-editor.NanoforgeClient.useGraphics",
  "core-editor.NanoforgeClient.useInput",
  "core-editor.NanoforgeClient.useSound",
  "core-editor.NanoforgeFactory",
  "core-editor.NanoforgeServer"
]);
}
