/**
 * Auto-generated type information for TypeTree components.
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on next generation.
 * 
 * Generated: 2026-05-31T10:05:11.588Z
 * Generated by: mint-tsdocs
 * 
 * @version 1.0.0
 */

/**
 * Type information organized by package and API item.
 * Use this to get TypeTreeProperty-compatible data for any documented type.
 * 
 * @example
 * ```jsx
 * import { TypeInfo } from "/snippets/tsdocs/TypeInfo.jsx"
 * 
 * <TypeTree open {...TypeInfo.MyPackage.MyInterface} />
 * 
 * // Or access nested properties:
 * const apiModelProp = TypeInfo.MintTsdocs.IMarkdownDocumenterOptions.properties.find(
 *   p => p.name === "apiModel"
 * );
 * ```
 */
export const TypeInfo = {
  "CoreEditor": {
    "NanoforgeClient": {
      "name": "NanoforgeClient",
      "type": "class"
    },
    "NanoforgeServer": {
      "name": "NanoforgeServer",
      "type": "class"
    }
  }
};
