/**
 * Auto-generated type declarations for TypeInfo.
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on next generation.
 * 
 * Generated: 2026-05-31T10:05:11.588Z
 * Generated by: mint-tsdocs
 * 
 * This file provides VSCode autocomplete for TypeInfo imports.
 * @version 1.0.0
 */

/**
 * TypeTree property structure
 */
export interface TypeTreeProperty {
  name: string;
  type: string;
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  defaultValue?: string;
  properties?: TypeTreeProperty[];
}

/**
 * Type information organized by package and API item.
 * Provides full autocomplete for all documented types.
 */
export const TypeInfo: {
  "CoreEditor": {
    "NanoforgeClient": {
      name: "NanoforgeClient";
      type: "class";
    };
    "NanoforgeServer": {
      name: "NanoforgeServer";
      type: "class";
    };
  };
};
